import type { Property } from "./types";

export const COMPANY = {
  name: import.meta.env.VITE_APP_NAME || "Night Light Connect",
  shortName: "Night Light",
  tagline: import.meta.env.VITE_TAGLINE || "Nigeria's trusted nationwide real estate & investment advisory.",
  whatsappNumber: import.meta.env.VITE_WHATSAPP_NUMBER || "09133172414",
  whatsappIntl: import.meta.env.VITE_WHATSAPP_INTL || "2349133172414",
  phone: import.meta.env.VITE_PHONE_NUMBER || "07080210062",
  phoneIntl: import.meta.env.VITE_PHONE_INTL || "+2347080210062",
  address: import.meta.env.VITE_ADDRESS || "23 High Court, Lekki-Ajah Road, Lagos, Nigeria",
  hours: "Mon – Sat: 8:00 AM – 7:00 PM",
  email: import.meta.env.VITE_EMAIL || "nightlighthomes171@gmail.com",
};

export const WHATSAPP_LINK = (text: string) =>
  `https://wa.me/${COMPANY.whatsappIntl}?text=${encodeURIComponent(text)}`;

export const PHONE_LINK = `tel:${COMPANY.phone}`;

export const NAV_LINKS = [
  { label: "Home", id: "home" },
  { label: "Properties", id: "properties" },
  { label: "About Us", id: "about" },
  { label: "Services", id: "services" },
  { label: "Why Choose Us", id: "why-us" },
  { label: "Contact", id: "contact" },
];

export const STATS = [
  { value: 36, suffix: "+", label: "States & FCT Covered" },
  { value: 500, suffix: "+", label: "Verified Properties Nationwide" },
  { value: 98, suffix: "%", label: "Due Diligence Pass Rate" },
  { value: 10, suffix: "+", label: "Nationwide Hubs" },
];

export const REGIONS = [
  {
    name: "South-West & Lagos",
    short: "SW",
    blurb: "Lekki, Ikoyi, Ajah, Ibadan, Abeokuta and the Ogun corridor",
    cities: "Lagos · Oyo · Ogun · Ondo · Osun · Ekiti",
    icon: "house" as const,
  },
  {
    name: "North-Central & FCT",
    short: "NC",
    blurb: "Abuja prime districts, Guzape, Maitama and the federal capital belt",
    cities: "FCT · Nasarawa · Niger · Plateau · Benue · Kogi",
    icon: "building" as const,
  },
  {
    name: "South-South",
    short: "SS",
    blurb: "Port Harcourt GRA, Asaba waterfronts, Uyo and the oil-city belt",
    cities: "Rivers · Delta · Akwa Ibom · Bayelsa · Cross River · Edo",
    icon: "map" as const,
  },
  {
    name: "South-East",
    short: "SE",
    blurb: "Enugu Golf Estate, Owerri, Onitsha and commercial nerve centres",
    cities: "Enugu · Imo · Anambra · Abia · Ebonyi",
    icon: "trend" as const,
  },
  {
    name: "North-West & Beyond",
    short: "NW",
    blurb: "Kano, Kaduna and emerging growth markets across the north",
    cities: "Kano · Kaduna · Katsina · Sokoto · Zamfara · Kebbi",
    icon: "key" as const,
  },
  {
    name: "Nationwide Land Banking",
    short: "NG",
    blurb: "Excision-verified farmland, corridor land and bulk industrial plots",
    cities: "All 36 States & FCT · Diaspora friendly",
    icon: "shield" as const,
  },
];

export const SERVICES = [
  {
    title: "Property Sales",
    desc: "Luxury duplexes, mansions and apartments with verified titles across Lagos, Abuja, Port Harcourt and beyond.",
    icon: "house" as const,
  },
  {
    title: "Rentals & Shortlets",
    desc: "Curated serviced apartments and shortlet advisory for executives, families and diaspora clients, nationwide.",
    icon: "key" as const,
  },
  {
    title: "Verified Land Sales",
    desc: "Land with genuine C of O, Governor's Consent, Gazette and Excision documentation in all regions of Nigeria.",
    icon: "map" as const,
  },
  {
    title: "Property Management",
    desc: "End-to-end facility oversight, tenant management and asset care for absentee owners across the country.",
    icon: "building" as const,
  },
  {
    title: "Investment Advisory",
    desc: "High-ROI portfolio guidance across prime Nigerian corridors, from Lekki to Abuja and the South-South.",
    icon: "trend" as const,
  },
  {
    title: "Title Verification",
    desc: "Due diligence that protects you from Omo Onile disputes, double sales and title defects, in every state.",
    icon: "shield" as const,
  },
];

export const WHY_US = [
  {
    title: "Trusted Guidance",
    desc: "Every recommendation is backed by honest, market-true counsel — no pressure, no hidden agendas.",
    icon: "heart" as const,
  },
  {
    title: "Verified Opportunities",
    desc: "We perform full title searches and land audits before any property enters our catalog, nationwide.",
    icon: "shield" as const,
  },
  {
    title: "Transparent Transactions",
    desc: "Clear pricing, open documentation and zero surprises from first viewing to handover.",
    icon: "eye" as const,
  },
  {
    title: "Professional Service",
    desc: "A dedicated team that treats your investment like our own — responsive, precise, courteous.",
    icon: "star" as const,
  },
  {
    title: "Customer-Centered",
    desc: "We listen first. Your budget, timeline and lifestyle shape every property we present.",
    icon: "users" as const,
  },
  {
    title: "Nationwide Reach",
    desc: "Verified partner networks and title liaisons in 36 states and the FCT, from one trusted HQ.",
    icon: "pin" as const,
  },
];

export const TESTIMONIALS = [
  {
    name: "Adaeze Okafor",
    role: "Diaspora Investor, UK",
    text: "Night Light Connect handled my Lekki duplex purchase from London. The title verification gave me total peace of mind — every document was clean before I sent a kobo.",
  },
  {
    name: "Ibrahim Sanni",
    role: "Tech Founder, Abuja",
    text: "They found me a serviced apartment in Abuja Guzape within a week. Professional from the first WhatsApp message to the handover of keys.",
  },
  {
    name: "Uche Obi",
    role: "Investor, Port Harcourt",
    text: "As an investor across the South-South I needed honest land titles. Their team walked me through everything and the Port Harcourt documents were thoroughly verified.",
  },
];

export const LOCATIONS = [
  "All Nigeria",
  "Lagos",
  "Abuja (FCT)",
  "Port Harcourt",
  "Ibadan",
  "Enugu",
  "Asaba / Delta",
  "Ogun State",
  "Kano",
];

export const TYPES = ["All Types", "Duplex", "Apartment", "Land", "Penthouse", "Terrace", "Commercial"];
export const PURPOSES = ["All Purposes", "sale", "rent", "shortlet"];

export const TITLE_TYPES = ["C of O", "Governor's Consent", "Gazette", "Excision / Deed of Assignment", "Registered Lease"];
export const STATUSES: Record<string, string> = {
  available: "Available",
  "under-offer": "Under Offer",
  reserved: "Reserved",
  sold: "Sold",
};

export const PRICE_UNITS = ["outright", "per annum", "per plot", "initial deposit", "per sqm"];
export const PROMO_BADGES = ["HOT DEAL", "PRICE REDUCED", "NEW RELEASE"] as const;

export const PRESET_IMAGES = [
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1400&q=80",
  "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=80",
];

export const ADMIN_PIN = import.meta.env.VITE_ADMIN_PIN || "2468";
export const BED_OPTIONS = ["Any Beds", "1", "2", "3", "4", "5+"];

export const DEFAULT_PROPERTIES: Property[] = [
  {
    id: "p1",
    title: "Luxury 4 Bedroom Fully Detached Duplex with BQ",
    slug: "luxury-4br-detached-duplex-lekki",
    location: "Lagos",
    area: "Lekki Phase 2",
    price: "₦165,000,000",
    priceNumeric: 165_000_000,
    type: "Duplex",
    purpose: "sale",
    beds: 4,
    baths: 5,
    areaSqm: 420,
    titleType: "Governor's Consent",
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80", alt: "Modern duplex exterior" },
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80", alt: "Luxury living room" },
      { url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=80", alt: "Open plan kitchen" },
    ],
    description:
      "A commanding 4-bedroom fully detached duplex with staff quarters, spacious living areas, a modern kitchen with granite finishes, and a private compound in a serene Lekki estate. Backed by Governor's Consent, this home is built for family comfort and long-term value.",
    features: [
      "Boys quarters (BQ) with ensuite",
      "Front & back gardens",
      "All rooms ensuite",
      "2 car parking + driver's quarters",
      "Pre-wired for smart home & solar",
      "24/7 estate security",
    ],
    coordinates: { label: "Lekki, Lagos" },
    status: "available",
  },
  {
    id: "p2",
    title: "Modern 3 Bedroom Serviced Apartment",
    slug: "modern-3br-serviced-apartment-abuja",
    location: "Abuja (FCT)",
    area: "Guzape",
    price: "₦120,000,000",
    priceNumeric: 120_000_000,
    type: "Apartment",
    purpose: "sale",
    beds: 3,
    baths: 3,
    areaSqm: 200,
    titleType: "C of O",
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80", alt: "Apartment building exterior" },
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80", alt: "Bedroom interior" },
      { url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=80", alt: "Bathroom interior" },
    ],
    description:
      "Bright, contemporary 3-bedroom serviced apartment in the heart of Abuja's Guzape district. Fully tiled, fitted kitchen with cabinets, POP ceilings and quick access to the city centre, schools and diplomatic enclave. Perfect for executives and rental-income investors.",
    features: [
      "Fitted kitchen with cabinets",
      "POP ceilings & LED lighting",
      "Dedicated parking",
      "Backup power & borehole",
      "Close to schools & malls",
      "C of O title document",
    ],
    coordinates: { label: "Guzape, Abuja FCT" },
    status: "available",
  },
  {
    id: "p3",
    title: "Premium Commercial / Residential Land for Sale",
    slug: "premium-commercial-residential-land-sangotedo",
    location: "Lagos",
    area: "Sangotedo",
    price: "₦45,000,000 / plot",
    priceNumeric: 45_000_000,
    type: "Land",
    purpose: "sale",
    beds: 0,
    baths: 0,
    areaSqm: 600,
    titleType: "Gazette",
    featured: false,
    images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80", alt: "Land with green fields" },
      { url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1400&q=80", alt: "Modern home on land" },
    ],
    description:
      "Choice 600sqm plot at the fast-developing Sangotedo axis — ideal for a commercial build, shortlet development or high-appreciation residential investment. Gazette-backed documentation, dry land, and direct access roads.",
    features: [
      "600sqm plot",
      "Gazette documentation",
      "Dry, free-flowing land",
      "Direct road access",
      "Rising commercial corridor",
      "Available for immediate development",
    ],
    coordinates: { label: "Sangotedo, Lagos" },
    status: "available",
  },
  {
    id: "p4",
    title: "Luxury 4 Bedroom Contemporary Family Home",
    slug: "luxury-4br-contemporary-family-home-ikota",
    location: "Lagos",
    area: "Ikota, Lekki",
    price: "₦140,000,000",
    priceNumeric: 140_000_000,
    type: "Duplex",
    purpose: "sale",
    beds: 4,
    baths: 4,
    areaSqm: 380,
    titleType: "Governor's Consent",
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80", alt: "Contemporary home exterior" },
      { url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=80", alt: "Elegant interior" },
      { url: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1400&q=80", alt: "Dining area" },
    ],
    description:
      "An elegant 4-bedroom contemporary family home in a peaceful Ikota estate. Double-volume living, imported fittings, landscaped compound and premium finishes throughout. Title documents verified with Governor's Consent.",
    features: [
      "Double-volume living room",
      "Imported sanitary fittings",
      "Landscaped compound",
      "Domestic staff quarters",
      "Borehole & inverter-ready",
      "Governor's Consent",
    ],
    coordinates: { label: "Ikota, Lekki" },
    status: "available",
  },
  {
    id: "p5",
    title: "Dry Residential Investment Land",
    slug: "dry-residential-investment-land-ibeju-lekki",
    location: "Lagos",
    area: "Ibeju-Lekki",
    price: "₦18,000,000",
    priceNumeric: 18_000_000,
    type: "Land",
    purpose: "sale",
    beds: 0,
    baths: 0,
    areaSqm: 500,
    titleType: "Excision / Deed of Assignment",
    featured: false,
    images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80", alt: "Land plot aerial" },
      { url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=80", alt: "Residential land development" },
    ],
    description:
      "Affordable entry into the Ibeju-Lekki growth corridor, minutes from the deep seaport and the Lekki Free Trade Zone. Dry, residential-zoned land with excision and deed documentation — a proven high-ROI investment.",
    features: [
      "Strategic growth corridor",
      "Near Lekki Deep Seaport",
      "Excision & deed papers",
      "Dry residential land",
      "Flexible payment plan",
      "Strong resale demand",
    ],
    coordinates: { label: "Ibeju-Lekki, Lagos" },
    status: "available",
  },
  {
    id: "p6",
    title: "Modern 4 Bedroom GRA Villa",
    slug: "modern-4br-gra-villa-port-harcourt",
    location: "Port Harcourt",
    area: "GRA Phase 2",
    price: "₦150,000,000",
    priceNumeric: 150_000_000,
    type: "Duplex",
    purpose: "sale",
    beds: 4,
    baths: 5,
    areaSqm: 400,
    titleType: "C of O",
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80", alt: "Modern villa exterior" },
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80", alt: "Master bedroom" },
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80", alt: "Spacious lounge" },
    ],
    description:
      "Sophisticated 4-bedroom villa in Port Harcourt's prestigious GRA Phase 2. Double-volume lounge, premium finishes, staff quarters and a secure compound close to the diplomatic zone and business district. C of O title verified.",
    features: [
      "Double-volume lounge",
      "Staff quarters",
      "Pre-wired for smart home & solar",
      "24/7 security",
      "2 car parking",
      "C of O title document",
    ],
    coordinates: { label: "GRA Phase 2, Port Harcourt" },
    status: "available",
  },
  {
    id: "p7",
    title: "Waterfront Land for Residential Development",
    slug: "waterfront-land-asaba-delta",
    location: "Asaba / Delta",
    area: "Asaba Waterfront",
    price: "₦32,000,000 / plot",
    priceNumeric: 32_000_000,
    type: "Land",
    purpose: "sale",
    beds: 0,
    baths: 0,
    areaSqm: 650,
    titleType: "Governor's Consent",
    featured: false,
    images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80", alt: "Waterfront land" },
      { url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1400&q=80", alt: "Development site" },
    ],
    description:
      "Prime 650sqm waterfront plot in Asaba, Delta State with Governor's Consent. Dry land with direct road access, ideal for a river-view residence or Airbnb development as the Asaba–Onitsha corridor grows.",
    features: [
      "650sqm waterfront plot",
      "Governor's Consent",
      "Direct road access",
      "Dry sand-filled land",
      "Asaba–Onitsha growth corridor",
      "Ideal for Airbnb development",
    ],
    coordinates: { label: "Asaba Waterfront, Delta" },
    status: "available",
  },
  {
    id: "p8",
    title: "Luxury 5 Bedroom Duplex in Guzape Estate",
    slug: "luxury-5br-duplex-guzape-abuja",
    location: "Abuja (FCT)",
    area: "Guzape",
    price: "₦185,000,000",
    priceNumeric: 185_000_000,
    type: "Duplex",
    purpose: "sale",
    beds: 5,
    baths: 6,
    areaSqm: 460,
    titleType: "Governor's Consent",
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80", alt: "Duplex exterior" },
      { url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=80", alt: "Luxury interior" },
      { url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=80", alt: "Ensuite bathroom" },
    ],
    description:
      "An imposing 5-bedroom duplex in Abuja's elite Guzape district, minutes from Maitama and the central business district. Imported finishes, a grand double-volume entrance, terraces and a landscaped compound with BQ. Governor's Consent verified.",
    features: [
      "Grand double-volume entrance",
      "Imported finishes",
      "Terraces with city views",
      "Boys quarters",
      "Borehole & inverter",
      "Governor's Consent",
    ],
    coordinates: { label: "Guzape, Abuja FCT" },
    status: "available",
  },
  {
    id: "p9",
    title: "Executive 3 Bedroom Terrace in Kolapo Ishola Estate",
    slug: "executive-3br-terrace-ibadan",
    location: "Ibadan",
    area: "Kolapo Ishola Estate",
    price: "₦85,000,000",
    priceNumeric: 85_000_000,
    type: "Terrace",
    purpose: "sale",
    beds: 3,
    baths: 4,
    areaSqm: 250,
    titleType: "C of O",
    featured: false,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80", alt: "Terrace rows" },
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80", alt: "Bedroom" },
      { url: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1400&q=80", alt: "Living area" },
    ],
    description:
      "Stylish 3-bedroom terrace in Ibadan's prime Kolapo Ishola Estate, a serene green community linked to the Lagos–Ibadan expressway and the city's commercial hub. Ideal for owner-occupiers and rental investors alike.",
    features: [
      "Gated, serviced estate",
      "Fitted kitchen",
      "2 car parking",
      "Borehole & power backup",
      "Close to expressway",
      "C of O title document",
    ],
    coordinates: { label: "Kolapo Ishola, Ibadan" },
    status: "available",
  },
  {
    id: "p10",
    title: "4 Bedroom Duplex in Golf Estate",
    slug: "4br-duplex-golf-estate-enugu",
    location: "Enugu",
    area: "Golf Estate",
    price: "₦95,000,000",
    priceNumeric: 95_000_000,
    type: "Duplex",
    purpose: "sale",
    beds: 4,
    baths: 4,
    areaSqm: 350,
    titleType: "C of O",
    featured: false,
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80", alt: "Duplex exterior" },
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80", alt: "Living room" },
      { url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=80", alt: "Bathroom" },
    ],
    description:
      "Contemporary 4-bedroom duplex inside Enugu's prestigious Golf Estate, offering secure living with landscaped grounds and premium fixtures. A rare find in the South-East with verified C of O documentation.",
    features: [
      "Secure gated estate",
      "Landscaped compound",
      "Fitted kitchen",
      "Borehole & inverter",
      "24/7 estate security",
      "C of O title document",
    ],
    coordinates: { label: "Golf Estate, Enugu" },
    status: "available",
  },
  {
    id: "p11",
    title: "Dry Commercial Plot, Ogun Corridor",
    slug: "dry-commercial-plot-ogun",
    location: "Ogun State",
    area: "Ota / Agbara Corridor",
    price: "₦28,000,000 / plot",
    priceNumeric: 28_000_000,
    type: "Land",
    purpose: "sale",
    beds: 0,
    baths: 0,
    areaSqm: 600,
    titleType: "Excision / Deed of Assignment",
    featured: false,
    images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80", alt: "Commercial land" },
      { url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1400&q=80", alt: "Development plot" },
    ],
    description:
      "Well-positioned 600sqm commercial plot on the busy Ota–Agbara industrial corridor in Ogun State, minutes from the Lagos border. Excision-backed land with high demand for warehouses, retail and logistics builds.",
    features: [
      "600sqm commercial plot",
      "Excision & deed papers",
      "Industrial corridor location",
      "Fast access to Lagos",
      "High warehouse demand",
      "Immediate development",
    ],
    coordinates: { label: "Ota, Ogun State" },
    status: "available",
  },
  {
    id: "p12",
    title: "Executive 2 Bedroom Shortlet, Maitama",
    slug: "executive-2br-shortlet-maitama-abuja",
    location: "Abuja (FCT)",
    area: "Maitama",
    price: "₦25,000,000 / per annum",
    priceNumeric: 25_000_000,
    type: "Apartment",
    purpose: "rent",
    beds: 2,
    baths: 2,
    areaSqm: 160,
    titleType: "Registered Lease",
    featured: false,
    images: [
      { url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80", alt: "Executive lounge" },
      { url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=80", alt: "Bedroom" },
      { url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=80", alt: "Bathroom" },
    ],
    description:
      "Premium 2-bedroom executive apartment in Maitama, Abuja's diplomatic quarter. Fully serviced with concierge, gym, backup power and high-speed internet. Perfect for diplomats, executives and short stays.",
    features: [
      "Fully serviced",
      "Diplomatic quarter location",
      "Concierge & security",
      "Gym & backup power",
      "High-speed internet",
      "Registered lease",
    ],
    coordinates: { label: "Maitama, Abuja FCT" },
    status: "available",
  },
];